kappa = 0.025       # Average frequency of groups in conflict
q = 0.01            # Splitting probability
n = 10              # Group size
m = 10              # Number of groups
b, c = 2.0, 1.0     # Benefit-cost ratio
z = 0.5             # Steepness of winning probability curve
alpha = 0.8         # Ingroup interaction frequency
lambda_mig = 0.0    # Migration rate
w = 0.1             # Intensity of selection
N=n*m               # Total population size